# Generated by Django 2.2.5 on 2019-10-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0004_try'),
    ]

    operations = [
        migrations.RenameField(
            model_name='try',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='try',
            old_name='tittle',
            new_name='title',
        ),
    ]
