# Generated by Django 2.2.5 on 2019-10-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0006_remove_labs_labcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Try',
        ),
        migrations.AddField(
            model_name='equipment',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
