# Generated by Django 2.2.5 on 2019-10-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0007_auto_20191005_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
